### ISSUE TITLE
Descrição da funcionalidade de Manter de Cliente/Fornecedores (Web)

### ISSUE THREAD

**Issue by kayronclay** [kayronclay/PSI_SZONE#11]

**Comment by golberysantos** [comment]
- Objetivo da Funcionalidade:  Registrar no sistema os dados dos clientes e fornecedores. Com o cadastro de clientes e forecedores a empresa poderá trabalhar com fidelização de cliente, promoções e ter o controle melhor dos seus fornecedores. Na mesma tela é possível Criar, Editar e Pesquisar Cliente/Fornecedor.

- Descrição da Funcionalidade: O usuário acessa a tela Cadastro Cliente Fornecedor, clica no menu Incluir e preenche os campos: CNPJ/CPF, Razão social, Nome Fantasia e finaliza clicando no botão Concluir.
Caso o usuário, por alguma razão, queira excluir o cadastro realizado deve clicar no menu Excluir. O sistema pergunta se o usuário deseja realmente excluir o cadastro e confima clicando no botão OK ou no botão Cancelar.
Para Editar, o usuário clica no menu Editar e faz as alterações necessárias, em seguida clica no botão concluir;
Para consultar um cliente/fornecedor o usuário clica no menu Pesquisar e fornece os dados para o sistema localizar o cliente/fornecedor.

- Itens de exceção na descrição da funcionalidade: 
1. O sistema valida se o CNPJ/CPF estiver errado;
2. O CNPJ/CPF e nome são campos obrigatórios
