### ISSUE TITLE
Descrição da funcionalidade de cadastro de usuários (Web)

### ISSUE THREAD

**Issue by kayronclay** [kayronclay/PSI_SZONE#14]

**Comment by golberysantos** [comment]
- Objetivo da Funcionalidade: Cadastrar os usuários para ter acesso ao sistema com login e senha.
- Descrição da Funcionalidade: O supervisor do sistema acessa a tela Cadastro Usuário, clica no botao incluir preenche os campos Login, Nome Usuário, e-mail, senha e clica no botao Concluir;
Ao clicar no botão Concluir será exibida a tela Grupo do Usuário o supervisor clica no menu Incluir Grupo;
